/*
Team Members:
Aamir Ibrahim
Bayleigh Correl
Adam Gonglach
Harry Haisty
 */
public enum TokenType
{
	FUNCTION_TOK, LEFT_PAREN_TOK, RIGHT_PAREN_TOK, IF_TOK, THEN_TOK, END_TOK, 
	ELSE_TOK, WHILE_TOK, DO_TOK, ID_TOK, PRINT_TOK, GE_TOK, GT_TOK, REPEAT_TOK,
	UNTIL_TOK,LE_TOK, LT_TOK, EQ_TOK, NE_TOK, ADD_TOK, SUB_TOK, MUL_TOK, 
	DIV_TOK, ASSIGN_TOK, EOS_TOK, LITERAL_INTEGER_TOK, CLASS_TOK, LEFT_BRACKET_TOK,
	RIGHT_BRACKET_TOK, STATIC_TOK, VOID_TOK, MAIN_TOK, STRING_ARR_TOK,
	ARGS_TOK, INTEGER_TOK, SEMICOLON_TOK, MODULO_TOK
}
